## This is development intended (cause the volumes...)
name: sleepr
services:
  
  reservations:
    container_name: reservations
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shared_services
    env_file:
      - ./apps/reservations/.env

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shared_services
    env_file:
    - ./apps/auth/.env

  payments:
    container_name: payments
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    ports:
      - '3003:3003'
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shared_services
    env_file:
    - ./apps/payments/.env

  mongo-db:
    container_name: mongo-db
    image: mongo # container image to be used
    restart: "no" 
    ports: # expose ports in “host:container” format
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment: #env variables to pass into the container
       MONGODB_DATABASE: sleepr
    networks:
      - shared_services

networks:
  shared_services:
    name: shared_services

volumes:
  mongo-data:
    name: 'mongo-data'